// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bagusays/efishery-technical-test/internal/shared/integration/efishery (interfaces: Client)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	efishery "github.com/bagusays/efishery-technical-test/internal/shared/integration/efishery"
	gomock "github.com/golang/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// FetchResource mocks base method.
func (m *MockClient) FetchResource(arg0 context.Context) ([]efishery.ResourceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchResource", arg0)
	ret0, _ := ret[0].([]efishery.ResourceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchResource indicates an expected call of FetchResource.
func (mr *MockClientMockRecorder) FetchResource(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchResource", reflect.TypeOf((*MockClient)(nil).FetchResource), arg0)
}
